### PR TITLE
V1 0 0 updates

### PR DESCRIPTION
**Pull request by georgenalen**
# Overall Review of Changes

Added the benchmark 1.0.0 changes

## Issue Fixes

N/A

## Enhancements

- Benchmark 1.0.0 changes

## How has this been tested?

Locally

Signed-off-by: George Nalen <georgen@mindpointgroup.com>

### CODE REVIEW

**Comment by georgenalen** [comment]
The Welcome check failed but the fix is in this PR.

**Comment by uk-bolly** [comment]
PR looks good warnings on actions items could be addressed.
Need to change actions/checkout@v2 to actions/checkout@v3. This is due to node12 EOL and moved to node16

**Review by uk-bolly — CHANGES_REQUESTED** [review]
Change actions/checkout@v2 to actions/checkout@v3
refer https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

**Review by uk-bolly — APPROVED** [review]
Looks good

**Pull request merged**
