### PR TITLE
Addressing issue 38

### PR DESCRIPTION
**Pull request by mfortin**
**Overall Review of Changes:**
Updating controls as per expected results from CIS Benchmark

**Issue Fixes:**
#38 

**Enhancements:**
None

**How has this been tested?:**
Tested by running role from this branch on a fresh instance

### CODE REVIEW

**Comment by MrSteve81** [comment]
Please Fix your Sign off for the DCO.  I have gone over this PR and It looks great thanks for the finds.

**Comment by mfortin** [comment]
@MrSteve81 fixed the DCO!

**Comment by frederickw082922** [comment]
Thank you @mfortin ! Great Catches! 

CC: @georgenalen @MrSteve81

**Review by MrSteve81 — COMMENTED** [review]
Approved

**Review by frederickw082922 — APPROVED** [review]
Approved!

**Comment by frederickw082922** [comment]
Good day @mfortin ! FYI, your commits are still populating not "Verified". Think options are Re-do your commits with "sign-off-by and verified"? Or I can do a new branch with your updates based on your PR #39?

**Review by frederickw082922 — CHANGES_REQUESTED** [review]
Not all the commits are signed with GPG signatures.

**Comment by mfortin** [comment]
Looks like I messed that up!

**Pull request closed without merging**
