### PR TITLE
Add 18.6.1, 18.6.2, 18.6.3

### PR DESCRIPTION
**Pull request by AnvaySingh**
Included 18.6.1, 18.6.2, 18.6.3 which are recommendations for printer settings.

# Overall Review of Changes

Included 3 tasks for section containing recommendations for printer settings present under '18.6 Printers' for CIS Microsoft Windows Server 2022 Benchmark.
18.6.1 (L1) Ensure 'Allow Print Spooler to accept client connections' is set to 'Disabled' (Automated)
18.6.2 (L1) Ensure 'Point and Print Restrictions: When installing drivers for a new connection' is set to 'Enabled: Show warning and elevation prompt' 
18.6.3 (L1) Ensure 'Point and Print Restrictions: When updating drivers for an existing connection' is set to 'Enabled: Show warning and elevation prompt'

## Issue Fixes

Please list (using linking) any open issues this PR addresses

## Enhancements

Please list any enhancements/features that are not open issue tickets

## How has this been tested?

N/A

Signed-off-by: Anvay Singh <anvaysingh05@gmail.com>

### CODE REVIEW

**Comment by georgenalen** [comment]
@AnvaySingh,
 Thanks for submitting the PR, it is greatly appreciated. I noticed the DCO is failing and that is due to not having the signed-off-by in your commit. Would you be able to update the commit to have that added? 

-George

**Review by georgenalen — APPROVED** [review]
Looks good!

**Comment by georgenalen** [comment]
@AnvaySingh,
 Thanks for updating the signed off that part is now there, however the gpg signature needs to be there as well. That is something you will need to setup in your GitHub account. How you know its' working is you get a green verified next to your commit. Once that one last DCO thing is updated I can then merge the PR. 

-George

**Comment by AnvaySingh** [comment]
@georgenalen 
I'm not sure about the gpg signature part here. I tried things here which I'm not sure if it's correct

**Comment by georgenalen** [comment]
@AnvaySingh,
 it looks like 2 of the three commits are verified and one is unverified, so it looks like the commit from 11ish am needs to be adjusted. Let me know if you end up not figuring out what the issue is, and we can figure out the best way forward. That might just be I can re-commit those changes with a mention to you and this PR. 

-George

**Pull request merged**
