### PR TITLE
Update control 1.1.6

### PR DESCRIPTION
**Pull request by mfortin**
**Overall Review of Changes:**
Control 1.1.6 can't be applied right now
```
TASK [Windows-2022-CIS : 1.1.6 | PATCH | Ensure Relax minimum password length limits is set to Enabled.] ***
fatal: [10.0.0.137]: FAILED! => changed=true
  import_log: |-
    Completed 1 percent (0/63)      Process Privilege Rights area
    Completed 3 percent (1/63)      Process Privilege Rights area
    Completed 4 percent (2/63)      Process Privilege Rights area
    Completed 6 percent (3/63)      Process Privilege Rights area
    Completed 7 percent (4/63)      Process Privilege Rights area
    Completed 9 percent (5/63)      Process Privilege Rights area
    Completed 11 percent (6/63)     Process Privilege Rights area
    Completed 12 percent (7/63)     Process Privilege Rights area
    Completed 14 percent (8/63)     Process Privilege Rights area
    Completed 15 percent (9/63)     Process Privilege Rights area
    Completed 17 percent (10/63)    Process Privilege Rights area
    Completed 19 percent (11/63)    Process Privilege Rights area
    Completed 20 percent (12/63)    Process Privilege Rights area
    Completed 25 percent (15/63)    Process Privilege Rights area
    Completed 25 percent (15/63)    Process Group Membership area
    Completed 49 percent (30/63)    Process Group Membership area
    Completed 49 percent (30/63)    Process Registry Keys area
    Completed 49 percent (30/63)    Process File Security area
    Completed 49 percent (30/63)    Process Services area
    Completed 65 percent (40/63)    Process Services area
    Completed 73 percent (45/63)    Process Services area
    Completed 73 percent (45/63)    Process Security Policy area
    Completed 77 percent (48/63)    Process Security Policy area
    Completed 84 percent (52/63)    Process Security Policy area
    Completed 88 percent (55/63)    Process Security Policy area
    Completed 93 percent (58/63)    Process Security Policy area
    Completed 100 percent (63/63)   Process Security Policy area
    The task has completed successfully.
  key: RelaxMinimumPasswordLengthLimits
  msg: The key 'RelaxMinimumPasswordLengthLimits' in section 'System Access' is not a valid key, cannot set this value
  section: System Access
  value: 1
```

**Issue Fixes:**
No issues created

**Enhancements:**
Enforces control id 1.1.6

**How has this been tested?:**
Locally, on an EC2 instance.

### CODE REVIEW

**Comment by mfortin** [comment]
@frederickw082922 can you restart this test build ?

**Comment by frederickw082922** [comment]
@mfortin  Thank you for the PR! Do not see the re-run workflow button on the validation. Not sure if actions/checkout@v3 has anything to do with it since there is an actions/checkout@v4.

CC: @MrSteve81

**Comment by mfortin** [comment]
@frederickw082922 I applied a simple commit to do the rebuild, it worked...

**Review by frederickw082922 — DISMISSED** [review]
Approved! Thank you @mfortin ! Good find! CC: @MrSteve81

**Review by MrSteve81 — DISMISSED** [review]
Approved

**Review by frederickw082922 — APPROVED** [review]
Thank you @mfortin !

**Review by MrSteve81 — APPROVED** [review]
Approved

**Pull request merged**
