### PR TITLE
Fixing issue #46

### PR DESCRIPTION
**Pull request by mfortin**
**Overall Review of Changes:**
Fixing issue #46 where post.yml is not executing

**Issue Fixes:**
#46 

**Enhancements:**
Performs a windows reboot when needed.

**How has this been tested?:**
Locally, by running the role fork.

### CODE REVIEW

**Comment by mfortin** [comment]
@frederickw082922 @MrSteve81 Please review

**Comment by MrSteve81** [comment]
Great catch! Will Have @frederickw082922 also look at it this morning.

**Review by MrSteve81 — APPROVED** [review]
Approved

**Review by MrSteve81 — COMMENTED** [review]
Approved

**Review by frederickw082922 — APPROVED** [review]
Looks good @mfortin ! Thank you!

**Pull request merged**
